language: ruby
rvm:
  - 2.3.1
before_install:
  - gem install bundler
  - gem update --system --source http://rubygems.org
  - gem --version
bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database usts_app_test;' -U postgres
sudo: required
dist: precise
