language: ruby
rvm:
  - 2.5.0
before_install:
  - gem update --system
  - gem --version
services:
  - postgresql
before_script:
  - psql -c 'create database usts_app_test;' -U postgres
sudo: required
dist: precise
