# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54887bcc8555510a46de96b4f32b468bcf6867fbac629d23ccf300b369a61be12a511573ea31a72ab03a22ec390e0de49bbd13b0f0b90941b08fc440d3293df4
  paypal_host: https://www.sandbox.paypal.com
  app_host: https://8d600ac2.ngrok.io
  paypal_merchant: merchant@gotealeaf.com

test:
  secret_key_base: 53678cff3f1f19255d9d4d97c8c77094d05ab2f99743a88d2ef484c18a4ddee8aa8b5a770f85f9baf2edfe8f9266708af36bd71c87f8175a83699266fac80a30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host: https://usts-app.herokuapp.com
  paypal_merchant: usts@optonline.net
